# Generated by Django 2.2.28 on 2022-09-01 13:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0149_auto_20220901_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypoContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(help_text='time to start racing', verbose_name='time start')),
                ('time_join', models.DateTimeField(help_text='time to participation join', verbose_name='time join')),
                ('limit', models.IntegerField(default=0, help_text='time limit', verbose_name='time limit')),
            ],
        ),
        migrations.CreateModel(
            name='TypoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('data', models.TextField()),
                ('difficult', models.CharField(choices=[('newbie', 'Newbie'), ('amateur', 'Amateur'), ('expert', 'Expert'), ('master', 'Master'), ('gmaster', 'Grand Master')], default='newbie', max_length=10, verbose_name='difficult')),
            ],
        ),
        migrations.CreateModel(
            name='TypoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_speed', models.FloatField(default=0, verbose_name='max speed')),
                ('date', models.DateTimeField(verbose_name='date created')),
                ('level', models.CharField(choices=[('newbie', 'Newbie'), ('amateur', 'Amateur'), ('expert', 'Expert'), ('master', 'Master'), ('gmaster', 'Grand Master')], default='newbie', max_length=10, verbose_name='level')),
            ],
        ),
        migrations.CreateModel(
            name='TypoRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('access_code', models.CharField(blank=True, default='', max_length=100, verbose_name='access code')),
                ('is_random', models.BooleanField(default=True, verbose_name='is random contest')),
                ('max_user', models.IntegerField(default=-1, verbose_name='max number user can participation')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='typeracer.TypoContest')),
            ],
        ),
        migrations.AddField(
            model_name='typocontest',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest', to='typeracer.TypoData'),
        ),
        migrations.CreateModel(
            name='TypoResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.time(0, 0), verbose_name='time')),
                ('speed', models.FloatField(default=0, verbose_name='speed')),
                ('ranked', models.BooleanField(default=False, verbose_name='is ranking')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('progress', models.IntegerField(default=0, verbose_name='progress')),
                ('is_finish', models.BooleanField(default=False, verbose_name='is finished')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='typeracer.TypoContest', verbose_name='contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typos', to='judge.Profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'typo result',
                'verbose_name_plural': 'typo results',
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
