# Generated by Django 2.2.28 on 2022-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeracer', '0002_typoroom_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='typocontest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='typoresult',
            name='time',
            field=models.FloatField(default=0, verbose_name='time'),
        ),
    ]
