# Generated by Django 2.2.24 on 2021-12-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0127_auto_20211207_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemdata',
            name='custom_checker',
        ),
        migrations.RemoveField(
            model_name='problemdata',
            name='custom_validator',
        ),
    ]
