# Generated by Django 2.2.24 on 2022-01-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0129_auto_20211207_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='first_accept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.ContestParticipation', verbose_name='first user accept this problem'),
        ),
    ]
