# Generated by Django 2.2.24 on 2022-02-12 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0129_auto_20211207_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('about', models.CharField(max_length=200, verbose_name='about')),
                ('link', models.URLField(blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name='link')),
                ('is_publish', models.BooleanField(db_index=True, default=False, verbose_name='Publish')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'permissions': (('edit_course', 'Edit all course'),),
            },
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='first_accept',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.ContestParticipation', verbose_name='first user accept this problem'),
        ),
        migrations.AddField(
            model_name='language',
            name='file_only',
            field=models.BooleanField(default=False, help_text='If this language is submitted using file or not', verbose_name='File-only language'),
        ),
        migrations.AddField(
            model_name='language',
            name='file_size_limit',
            field=models.IntegerField(blank=True, default=0, help_text='Limit of file size (in MB) if allow submit via file', verbose_name='Limit of file size'),
        ),
        migrations.AddField(
            model_name='navigationbar',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Only superuser can view link', verbose_name='Admin view'),
        ),
        migrations.AlterField(
            model_name='language',
            name='key',
            field=models.CharField(help_text='The identifier for this language; the same as its executor id for judges.', max_length=10, unique=True, verbose_name='short identifier'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text="Doesn't have magic ability to auto-publish due to backward compatibility", null=True, verbose_name='date of publishing'),
        ),
    ]
