# Generated by Django 2.2.24 on 2022-02-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0130_auto_20220212_0944'),
    ]
    
    replaces = [
        ('judge', '0131_profile_current_exam'),
        ('judge', '0132_profile_emath')
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emath',
            field=models.BooleanField(default=False, verbose_name='Emath'),
        ),
    ]
