# Generated by Django 2.2.24 on 2022-01-27 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0130_contestproblem_first_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='first_accept',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.ContestParticipation', verbose_name='first user accept this problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text="Doesn't have magic ability to auto-publish due to backward compatibility", null=True, verbose_name='date of publishing'),
        ),
    ]
