# Generated by Django 2.2.24 on 2022-02-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0130_auto_20220212_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emath.ExamParticipation', verbose_name='current exam'),
        ),
    ]
