# Generated by Django 2.2.24 on 2022-01-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emath', '0001_initial'),
        ('judge', '0131_auto_20220127_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emath.ExamParticipation', verbose_name='current exam'),
        ),
    ]
