# Generated by Django 2.2.24 on 2022-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0132_profile_current_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('about', models.CharField(max_length=200, verbose_name='about')),
                ('link', models.URLField(blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name='link')),
                ('is_publish', models.BooleanField(db_index=True, default=False, verbose_name='Publish')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'permissions': (('edit_course', 'Edit all course'),),
            },
        ),
    ]
