# Generated by Django 2.2.24 on 2022-02-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0132_profile_emath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='rating_ceiling',
            field=models.IntegerField(default=1000, help_text='Rating ceiling for contest', verbose_name='rating ceiling'),
        ),
    ]
