# Generated by Django 2.2.24 on 2022-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0133_auto_20220225_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='rating_ceiling',
            field=models.IntegerField(choices=[(1000, 'Newbie'), (1200, 'Amateur'), (1500, 'Expert'), (1800, 'Candidate Master'), (2200, 'Master'), (3000, 'Grandmaster'), (4000, 'Target')], default=1000, help_text='Rating ceiling for contest', verbose_name='rating ceiling'),
        ),
    ]
