# Generated by Django 2.2.24 on 2022-02-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0134_auto_20220210_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='file_only',
            field=models.BooleanField(default=False, help_text='If this language is submitted using file or not', verbose_name='File-only language'),
        ),
        migrations.AddField(
            model_name='language',
            name='file_size_limit',
            field=models.IntegerField(blank=True, default=0, help_text='Limit of file size (in MB) if allow submit via file', verbose_name='Limit of file size'),
        ),
    ]
