# Generated by Django 2.2.24 on 2022-02-28 15:08

import datetime
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0136_profile_last_change_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='prev name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_change_name',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 15, 8, 45, 200559, tzinfo=datetime.timezone.utc), verbose_name='last change fullname'),
        ),
    ]
