# Generated by Django 2.2.24 on 2022-03-29 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0138_auto_20220324_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='rating_ceiling',
            field=models.IntegerField(choices=[(1000, 'Newbie'), (1300, 'Amateur'), (1600, 'Expert'), (1900, 'Candidate Master'), (2400, 'Master'), (3000, 'Grandmaster'), (4000, 'Target')], default=1000, help_text='Rating ceiling for contest', verbose_name='rating ceiling'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rate',
            field=models.IntegerField(choices=[(1000, 'Newbie'), (1300, 'Amateur'), (1600, 'Expert'), (1900, 'Candidate Master'), (2400, 'Master'), (3000, 'Grandmaster'), (4000, 'Target')], default=1000, verbose_name='Rate of Organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_change_name',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 13, 5, 33, 893036, tzinfo=utc), verbose_name='last change fullname'),
        ),
    ]
