# Generated by Django 2.2.24 on 2022-04-01 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0139_auto_20220329_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='problem class ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='problem class name')),
            ],
            options={
                'verbose_name': 'problem class',
                'verbose_name_plural': 'problem classes',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_change_name',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 11, 31, 40, 747019, tzinfo=utc), verbose_name='last change fullname'),
        ),
        migrations.AddField(
            model_name='problem',
            name='classes',
            field=models.ForeignKey(help_text='The class of problem, shown under Class in the problem list.', null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.ProblemClass', verbose_name='problem class'),
        ),
    ]
