# Generated by Django 2.2.24 on 2022-04-02 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0140_auto_20220401_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[('atcoder', 'AtCoder'), ('default', 'Default'), ('ecoo', 'ECOO'), ('icpc', 'ICPC'), ('ioi', 'IOI (pre-2016)'), ('ioi16', 'IOI'), ('tmath', 'Tmath')], default='default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='classes',
            field=models.ForeignKey(help_text='The class of problem, shown under Class in the problem list.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.ProblemClass', verbose_name='problem class'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='group',
            field=models.ForeignKey(help_text='The group of problem, shown under Category in the problem list.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.ProblemGroup', verbose_name='problem group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_change_name',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 7, 51, 48, 520322, tzinfo=datetime.timezone.utc), verbose_name='last change fullname'),
        ),
    ]
