# Generated by Django 2.2.24 on 2022-04-05 04:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0142_auto_20220402_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'permissions': (('test_site', 'Shows in-progress development stuff'), ('totp', 'Edit TOTP settings')), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='contest',
            name='is_full_markup',
            field=models.BooleanField(default=False, verbose_name='markup full'),
        ),
        migrations.AddField(
            model_name='solution',
            name='is_full_markup',
            field=models.BooleanField(default=False, verbose_name='markup full'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_change_name',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 4, 23, 11, 470959, tzinfo=utc), verbose_name='last change fullname'),
        ),
    ]
