# Generated by Django 2.2.24 on 2022-06-17 06:15

import datetime
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0145_auto_20220416_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emath',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_change_name',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 6, 15, 51, 523755, tzinfo=datetime.timezone.utc), verbose_name='last change fullname'),
        ),
    ]
