# Generated by Django 2.2.28 on 2022-07-10 16:19

from django.db import migrations, models
import django.db.models.deletion
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0146_auto_20220617_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='code for this contest level', max_length=50, unique=True, verbose_name='code')),
                ('about', models.CharField(help_text='detail for this contest level', max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'contest level',
                'verbose_name_plural': 'contest levels',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_change_name',
            field=models.DateTimeField(default=judge.models.profile.get_default_time, verbose_name='last change fullname'),
        ),
        migrations.AddField(
            model_name='samplecontest',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.ContestLevel', verbose_name='contest level'),
        ),
        migrations.AddField(
            model_name='samplecontestproblem',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.ContestLevel', verbose_name='level'),
        ),
    ]
