# Generated by Django 2.2.28 on 2022-09-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0148_problem_testcase_visibility_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('key',), 'verbose_name': 'license', 'verbose_name_plural': 'licenses'},
        ),
    ]
