# Generated by Django 2.2.28 on 2022-09-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typeracer', '0001_initial'),
        ('judge', '0149_auto_20220901_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typo_contest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='typeracer.TypoContest', verbose_name='current typo contest'),
        ),
    ]
