# Generated by Django 3.2.15 on 2022-09-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0151_auto_20220903_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='problem category ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='problem category name')),
            ],
            options={
                'verbose_name': 'problem category',
                'verbose_name_plural': 'problem categories',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='add_solution',
            field=models.BooleanField(default=False, verbose_name='can add solution'),
        ),
        migrations.AddField(
            model_name='contest',
            name='limit_solution',
            field=models.IntegerField(default=0, verbose_name='limit solution'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='problem type name'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='problem type ID'),
        ),
        migrations.CreateModel(
            name='PublicSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='solution')),
                ('score', models.IntegerField(default=0, verbose_name='votes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('approved', models.BooleanField(default=False, verbose_name='is approved')),
                ('point', models.IntegerField(default=0, verbose_name='point')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile', verbose_name='user')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.contest', verbose_name='contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem', verbose_name='problem')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SolutionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='judge.publicsolution')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_solutions', to='judge.profile')),
            ],
            options={
                'verbose_name': 'solution vote',
                'verbose_name_plural': 'solution votes',
                'unique_together': {('voter', 'solution')},
            },
        ),
    ]
