# Generated by Django 3.2.15 on 2022-10-01 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0152_auto_20220926_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
                ('object_id', models.IntegerField(verbose_name='object id')),
                ('object_title', models.CharField(max_length=255, verbose_name='object title')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'logging',
                'ordering': ('-time',),
            },
        ),
    ]
