# Generated by Django 3.2.15 on 2022-10-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0153_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrequest',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='judge.profile', verbose_name='admin'),
        ),
    ]
