# Generated by Django 3.2.16 on 2022-11-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0155_auto_20221028_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestparticipation',
            name='cumtime',
            field=models.PositiveBigIntegerField(default=0, verbose_name='cumulative time'),
        ),
    ]
