# Generated by Django 3.2.16 on 2022-11-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0157_auto_20221106_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='grader_args',
            field=models.TextField(blank=True, help_text='grader arguments as a JSON object', verbose_name='grader arguments'),
        ),
    ]
