# Generated by Django 3.2.16 on 2022-12-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0160_problemtype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='public_description',
            field=models.BooleanField(default=False, verbose_name="public description' problem"),
        ),
    ]
