# Generated by Django 3.2.16 on 2023-03-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0163_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_limit_language',
            field=models.BooleanField(default=False, verbose_name='language restriction'),
        ),
        migrations.AddField(
            model_name='contest',
            name='limit_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.language', verbose_name='limit language'),
        ),
    ]
