# Generated by Django 3.2.16 on 2023-03-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0164_auto_20230301_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_public_contest',
            field=models.BooleanField(default=False, verbose_name='Public contest'),
        ),
    ]
