# Generated by Django 3.2.18 on 2023-05-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0167_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='topic',
            field=models.CharField(blank=True, max_length=100, verbose_name='contest topic'),
        ),
    ]
