# Generated by Django 3.2.18 on 2023-05-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0168_contest_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='contest name'),
        ),
    ]
