# Generated by Django 2.2.24 on 2022-04-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0144_auto_20220411_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Room title')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='judge.Organization', unique=True, verbose_name='Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ChatParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom', verbose_name='Room chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Profile', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='Message')),
                ('publish_on', models.DateTimeField(auto_now_add=True, verbose_name='Time publish')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom', verbose_name='Chat room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatParticipation', verbose_name='User')),
            ],
        ),
    ]
