# Generated by Django 2.2.24 on 2022-02-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emath', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsubmission',
            options={'verbose_name': 'exam submission', 'verbose_name_plural': 'exam submissions'},
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='case_points',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='case_total',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='current_testcase',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='exam_object',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='judged_date',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='locked_after',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='rejudged_date',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='result',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='time',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='format_name',
            field=models.CharField(choices=[('default', 'Default')], default='default', help_text='The exam format module to use.', max_length=32, verbose_name='exam format'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', related_query_name='submission', to='emath.Exam', verbose_name='exam'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', related_query_name='submission', to='emath.ExamParticipation', verbose_name='participation'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='submission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='emath.Submission', verbose_name='submission'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='points',
            field=models.FloatField(default=0.0, verbose_name='points'),
        ),
        migrations.CreateModel(
            name='SubmissionProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False, verbose_name='result for this problem')),
                ('points', models.FloatField(null=True, verbose_name='points granted')),
                ('output', models.TextField(blank=True, verbose_name="Student's answer")),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emath.ExamProblem', verbose_name='problem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='emath.Submission', verbose_name='submission')),
            ],
            options={
                'verbose_name': 'submission problem',
                'verbose_name_plural': 'submission problems',
                'unique_together': {('submission', 'problem')},
            },
        ),
    ]
