# Generated by Django 2.2.24 on 2022-02-19 12:31

from django.db import migrations, models
import django.db.models.deletion
import judge.models.interface
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emath', '0002_auto_20220219_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('key', models.CharField(max_length=10, unique=True, verbose_name='identifier')),
                ('label', models.CharField(max_length=20, verbose_name='label')),
                ('path', models.CharField(max_length=255, verbose_name='link path')),
                ('regex', models.TextField(validators=[judge.models.interface.validate_regex], verbose_name='highlight regex')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='emath.Navigation', verbose_name='parent item')),
            ],
            options={
                'verbose_name': 'navigation item',
                'verbose_name_plural': 'navigation bar',
            },
        ),
    ]
