# Generated by Django 2.2.24 on 2022-02-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emath', '0004_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
