# Generated by Django 2.2.24 on 2022-02-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emath', '0005_auto_20220225_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, help_text='One number that is the answer of this problem.', max_length=50, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='wrong_answer1',
            field=models.CharField(blank=True, default=None, help_text='One number that is a wrong answer of this problem.', max_length=50, verbose_name='wrong answer'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='wrong_answer2',
            field=models.CharField(blank=True, default=None, help_text='One number that is a wrong answer of this problem.', max_length=50, verbose_name='wrong answer'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='wrong_answer3',
            field=models.CharField(blank=True, default=None, help_text='One number that is a wrong answer of this problem.', max_length=50, verbose_name='wrong answer'),
        ),
    ]
