# Generated by Django 2.2.24 on 2022-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emath', '0007_auto_20220226_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='rate',
            field=models.IntegerField(choices=[(1000, 'Newbie'), (1200, 'Amateur'), (1500, 'Expert'), (1800, 'Candidate Master'), (2200, 'Master'), (3000, 'Grandmaster'), (4000, 'Target')], default=1000, verbose_name='Rate of Organization'),
        ),
    ]
