# Generated by Django 3.2.16 on 2023-05-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emath', '0009_auto_20220329_1305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examparticipation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='examparticipation',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examparticipation',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='examproblem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='examproblem',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examproblem',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='participation',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='submission',
        ),
        migrations.AlterUniqueTogether(
            name='submissionproblem',
            unique_together={('submission', 'id')},
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamParticipation',
        ),
        migrations.DeleteModel(
            name='ExamSubmission',
        ),
        migrations.RemoveField(
            model_name='submissionproblem',
            name='problem',
        ),
        migrations.DeleteModel(
            name='ExamProblem',
        ),
    ]
