# Generated by Django 3.2.16 on 2023-05-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emath', '0010_auto_20230514_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='organizationrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='submissionproblem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='submissionproblem',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='organizations',
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationRequest',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='SubmissionProblem',
        ),
    ]
