# Generated by Django 3.2.16 on 2023-05-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emath', '0011_auto_20230514_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='group',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='MathGroup',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
